<?php
return [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
	"Hac habitasse platea dictumst vestibulum.",
	"Lectus mauris ultrices eros in cursus turpis massa.",
	"Pellentesque massa placerat duis ultricies lacus sed.",
	"Mauris pharetra et ultrices neque ornare aenean.",
	"Integer feugiat scelerisque varius morbi enim nunc faucibus a.",
	"Tellus mauris a diam maecenas sed.",
	"Quis ipsum suspendisse ultrices gravida.",
	"Nam at lectus urna duis convallis convallis.",
	"Rhoncus dolor purus non enim praesent elementum facilisis leo vel.",
	"Mauris vitae ultricies leo integer malesuada nunc vel risus.",
	"Vitae turpis massa sed elementum tempus.",
	"Ac placerat vestibulum lectus mauris ultrices eros in cursus.",
	"Sed euismod nisi porta lorem mollis aliquam.",
	"Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt.",
	"Magna ac placerat vestibulum lectus mauris ultrices eros.",
	"Massa tincidunt nunc pulvinar sapien et ligula.",
	"Diam maecenas sed enim ut sem viverra aliquet eget.",
	"Nisl rhoncus mattis rhoncus urna neque viverra justo.",
	"Arcu non sodales neque sodales ut etiam sit amet.",
	"Vitae sapien pellentesque habitant morbi.",
	"Neque gravida in fermentum et sollicitudin ac orci phasellus.",
	"Sed risus ultricies tristique nulla aliquet enim tortor.",
	"Aliquam purus sit amet luctus.",
	"Vitae justo eget magna fermentum iaculis.",
	"Sit amet justo donec enim diam vulputate ut pharetra.",
	"Quis lectus nulla at volutpat diam ut venenatis.",
	"At auctor urna nunc id cursus metus aliquam eleifend mi.",
	"Quam pellentesque nec nam aliquam sem et tortor.",
	"Purus gravida quis blandit turpis cursus in hac habitasse platea.",
	"Ac feugiat sed lectus vestibulum.",
	"Cras adipiscing enim eu turpis egestas pretium aenean pharetra.",
	"Pellentesque habitant morbi tristique senectus et netus et.",
	"Varius duis at consectetur lorem donec massa sapien faucibus.",
	"Habitasse platea dictumst vestibulum rhoncus est pellentesque elit.",
	"Mattis aliquam faucibus purus in massa tempor nec feugiat.",
	"Eu ultrices vitae auctor eu augue ut.",
	"At ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget.",
	"Semper feugiat nibh sed pulvinar proin.",
	"Quisque id diam vel quam elementum pulvinar etiam non quam.",
	"Id semper risus in hendrerit gravida rutrum quisque.",
	"Dignissim convallis aenean et tortor at risus.",
	"Hendrerit dolor magna eget est lorem ipsum dolor sit amet.",
	"At augue eget arcu dictum.",
	"Massa eget egestas purus viverra.",
	"Neque ornare aenean euismod elementum nisi quis eleifend.",
	"Arcu felis bibendum ut tristique et egestas quis ipsum.",
	"Sit amet tellus cras adipiscing enim eu.",
	"Sagittis purus sit amet volutpat consequat mauris.",
	"Nullam non nisi est sit amet facilisis magna etiam tempor.",
	"Consequat nisl vel pretium lectus quam id leo in.",
	"Et malesuada fames ac turpis egestas integer eget aliquet nibh.",
	"Blandit cursus risus at ultrices mi tempus imperdiet.",
	"Sed viverra tellus in hac habitasse platea dictumst vestibulum.",
	"Gravida quis blandit turpis cursus in hac habitasse platea.",
	"Sagittis orci a scelerisque purus semper.",
	"Porttitor leo a diam sollicitudin tempor id eu nisl nunc.",
	"Quisque non tellus orci ac auctor.",
	"Cras semper auctor neque vitae tempus quam pellentesque.",
	"Metus vulputate eu scelerisque felis.",
	"Vitae sapien pellentesque habitant morbi tristique senectus et.",
	"Eget duis at tellus at urna condimentum.",
	"Tempor orci eu lobortis elementum nibh tellus molestie nunc non.",
	"Eleifend mi in nulla posuere sollicitudin aliquam.",
	"Risus sed vulputate odio ut enim blandit volutpat maecenas.",
	"Pellentesque sit amet porttitor eget dolor morbi non arcu.",
	"At lectus urna duis convallis convallis tellus id.",
	"Ut sem viverra aliquet eget sit.",
	"Tristique senectus et netus et malesuada fames ac turpis egestas.",
	"In vitae turpis massa sed elementum.",
	"Mattis molestie a iaculis at erat pellentesque adipiscing.",
	"Est placerat in egestas erat imperdiet sed euismod nisi.",
	"Leo integer malesuada nunc vel risus commodo viverra maecenas.",
	"Nisl suscipit adipiscing bibendum est ultricies integer quis.",
	"Nam aliquam sem et tortor consequat id porta nibh venenatis.",
	"Est placerat in egestas erat imperdiet sed euismod.",
	"Vel risus commodo viverra maecenas accumsan lacus vel facilisis.",
	"Nibh tellus molestie nunc non blandit massa.",
	"Ornare aenean euismod elementum nisi quis eleifend quam.",
	"Egestas purus viverra accumsan in nisl nisi scelerisque eu ultrices.",
	"Adipiscing bibendum est ultricies integer.",
	"Lorem ipsum dolor sit amet consectetur adipiscing elit.",
	"Mattis nunc sed blandit libero volutpat sed cras ornare.",
	"Adipiscing commodo elit at imperdiet.",
	"Amet purus gravida quis blandit.",
	"Convallis tellus id interdum velit.",
	"Adipiscing at in tellus integer feugiat scelerisque varius morbi enim.",
	"In hac habitasse platea dictumst vestibulum.",
	"Et tortor at risus viverra adipiscing.",
	"Interdum posuere lorem ipsum dolor.",
	"Congue mauris rhoncus aenean vel.",
	"Suscipit adipiscing bibendum est ultricies integer quis auctor elit.",
	"At elementum eu facilisis sed odio morbi quis.",
	"Vitae congue eu consequat ac felis donec et.",
	"Habitant morbi tristique senectus et netus et malesuada fames ac.",
	"Scelerisque viverra mauris in aliquam.",
	"Vulputate eu scelerisque felis imperdiet proin fermentum leo vel orci.",
	"Gravida dictum fusce ut placerat orci nulla pellentesque.",
	"Enim sit amet venenatis urna cursus eget nunc.",
	"Non arcu risus quis varius quam quisque id diam."
];
?>
